#>>>>>>>>>> Tomcat Server 설정  <<<<<<<<<<<<
server:
  port: 8090

#>>>>>>>>>> MariaDB 설정  <<<<<<<<<<<<
#3333/DB이름 설정 주의
#>>>>>>>>>> JPA 설정  <<<<<<<<<<<<
#배포시 true로 변경, 개발용이 false래서 설정해둠
spring:
  datasource:
    username: dude
    password: 1234
    url: jdbc:mariadb://localhost:3333/dudedb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true

#>>>>>>>>>> Logging 설정  <<<<<<<<<<<<
logging:
  level:
    org.springframework.web: debug
    org.hibernate.sql: debug
    jpa: debug
